"""empty message

Revision ID: 011bd8afe0ad
Revises: d897fb0ec992
Create Date: 2023-03-11 22:39:52.245620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '011bd8afe0ad'
down_revision = 'd897fb0ec992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bedrooms', sa.Integer(), nullable=True))
        batch_op.drop_column('rooms')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rooms', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('bedrooms')

    # ### end Alembic commands ###
