"""empty message

Revision ID: 0938edb297e1
Revises: 3efa543cde1c
Create Date: 2023-03-12 14:08:09.768654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0938edb297e1'
down_revision = '3efa543cde1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_profiles', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_profiles', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)

    # ### end Alembic commands ###
