"""empty message

Revision ID: 16cb35d045af
Revises: cc0f17ef976a
Create Date: 2023-03-11 23:25:47.163795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16cb35d045af'
down_revision = 'cc0f17ef976a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_profiles', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.VARCHAR(length=180),
               type_=sa.String(length=80),
               existing_nullable=True)
        batch_op.alter_column('photo_filename',
               existing_type=sa.VARCHAR(length=180),
               type_=sa.String(length=80),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_profiles', schema=None) as batch_op:
        batch_op.alter_column('photo_filename',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=180),
               existing_nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=180),
               existing_nullable=True)

    # ### end Alembic commands ###
