"""empty message

Revision ID: 67a9613baf7e
Revises: 16cb35d045af
Create Date: 2023-03-11 23:38:36.759354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67a9613baf7e'
down_revision = '16cb35d045af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_profiles', schema=None) as batch_op:
        batch_op.alter_column('desc',
               existing_type=sa.VARCHAR(length=180),
               type_=sa.String(length=160),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_profiles', schema=None) as batch_op:
        batch_op.alter_column('desc',
               existing_type=sa.String(length=160),
               type_=sa.VARCHAR(length=180),
               existing_nullable=True)

    # ### end Alembic commands ###
