"""empty message

Revision ID: ad4d47073dd5
Revises: 67a9613baf7e
Create Date: 2023-03-11 23:54:50.904578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad4d47073dd5'
down_revision = '67a9613baf7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_profiles', schema=None) as batch_op:
        batch_op.alter_column('desc',
               existing_type=sa.VARCHAR(length=160),
               type_=sa.String(length=250),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_profiles', schema=None) as batch_op:
        batch_op.alter_column('desc',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=160),
               existing_nullable=True)

    # ### end Alembic commands ###
