"""empty message

Revision ID: cc0f17ef976a
Revises: 
Create Date: 2023-03-11 23:14:48.598166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc0f17ef976a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=True),
    sa.Column('desc', sa.String(length=180), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('price', sa.String(length=180), nullable=True),
    sa.Column('property_type', sa.String(length=80), nullable=True),
    sa.Column('location', sa.String(length=180), nullable=True),
    sa.Column('photo_filename', sa.String(length=180), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property_profiles')
    # ### end Alembic commands ###
